# docker compose -f docker-compose-local.yaml down
# 使用wsl2安装consul: https://developer.hashicorp.com/consul/install#linux
# 以开发模式启动consul: consul agent -dev
version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d

  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"