version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379