// Copyright 2024 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by hertz generator. DO NOT EDIT.

package home

import (
	home "github.com/cloudwego/biz-demo/gomall/app/frontend/biz/handler/home"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// 此文件将注册 master idl 中服务的所有路由。 当您对 idl 使用 “update” 命令时，它会自动更新。
// 所以不要修改文件的内容，否则你的代码会在更新时被删除。

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	root.GET("/", append(_homeMw(), home.Home)...)
}
