# Promtail 是一个用于收集和转发日志的工具，通常与 Grafana Loki 配合使用。
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: hertz
    pipeline_stages:
      - json:
          expressions:
            level: level
      - labels:
          level:
    static_configs:
      - targets:
          - localhost
        labels:
          app: frontend
          __path__: /logs/frontend/hertz.log